name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # the deploy step pushes the build to the gh-pages branch
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install and Build 🔧
        run: |
          yarn
          yarn build:index
          mv notes public/notes
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: www
